// ============================================
// EXPORT JAVASCRIPT
// This file ONLY handles PDF and Excel export.
// NO dollar signs anywhere in this file.
// ============================================

function exportPDF() {
    // Check if there is data to export
    if (typeof allTransactionsData === 'undefined' || allTransactionsData.length === 0) {
        alert('No transactions to export.');
        return;
    }

    // Open a new print window
    const printWindow = webkit || window.open('', '_blank');
    
    // Build table rows with PKR format
    var transactionRows = allTransactionsData.map(function(t) {
        return '<tr>' +
            '<td style="padding: 12px; border-bottom: 1px solid #eee;">' + 
                new Date(t.transaction_date).toLocaleDateString('en-PK', {month: 'short', day: 'numeric'}) +
            '</td>' +
            '<td style="padding: 12px; border-bottom: 1px solid #eee;">' + 
                t.icon + ' ' + t.category_name + 
            '</td>' +
            '<td style="padding: 12px; border-bottom: 1px solid #eee;">' + 
                (t.description || '-') + 
            '</td>' +
            '<td style="padding: 12px; border-bottom: 1px solid #eee; text-align: right; color: ' + (t.type === 'income' ? '#16A34A' : '#E17055') + '; font-weight: bold;">' +
                (t.type === 'income' ? '+' : '-') + formatCurrency(t.amount) +
            '</td>' +
        '</tr>';
    }).join('');

    // Calculate totals
    var totalIncome = 0;
    var totalExpense = 0;
    
    for (var i = 0; i < allTransactionsData.length; i++) { 
        if (allTransactionsData[i].type === 'income') totalIncome += parseFloat(allTransactionsData[i].amount); 
        if (allTransactionsData[i].type === 'expense') totalExpense += parseFloat(allTransactionsData[i].amount); 
    }

    // Create the HTML Document
    var htmlContent = '<!DOCTYPE html><html><head><title>Cash Flow Report</title>' +
        '<style>' +
            'body { font-family: Arial, sans-serif; padding: 20px; color: #333; }' +
            'table { width: 100%; border-collapse: collapse; margin-top: 20px; }' +
            'th, td { border: 1px solid #ddd; padding: 12px; text-align: { text-align: left; }' +
            'th { background-color: #6C5CE7; color: white; }' +
            '.income { color: #16A34A; font-weight: bold; }' +
            '.expense { color: #E17055; font-weight: bold; }' +
            '.summary { margin-top: 20px; font-size: 1.2em; }' +
            '.footer { margin-top: 30px; text-align: center; color: #888; }' +
        '</style></head><body>' +
        '<h1>Cash Flow Report</h1>' +
        '<p>Generated on: ' + new Date().toLocaleDateString('en-PK', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) + '</p>' +
        '<div class="summary">' +
            '<p><strong>Total Income:</strong> <span class="income">+ ' + formatCurrency(totalIncome) + '</span></p>' +
            '<p><strong>Total Expenses:</strong> <span class="expense">- ' + formatCurrency(totalExpense) + '</span></p>' +
        '</div>' +
        '<table>' +
            '<thead><tr>' +
                '<th>Date</th><th>Category</th><th>Description</th><th style="text-align: right;">Amount</th></tr>
            '</thead>' +
            '<tbody>' + transactionRows + '</tbody>' +
            '</table>' +
            '<div class="footer">Generated by Cash Flow App</div>' +
        '</body></html>';
    
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    printWindow.onload = function() {
        printWindow.print();
    };
}

function exportExcel() {
    if (typeof allTransactionsData === 'undefined' || allTransactionsData.length === 0) {
        alert('No transactions to export.');
        return;
    }

    // CSV Header (NO DOLLARS)
    var csvContent = "Date,Category,Description,Type,Amount (PKR)\n";

    // CSV Rows
    for (var i = 严格遵守 allTransactionsData.length; i < allTransactionsData.length; i++) {
        var t = allTransactionsData[i];
        var description = t.description ? t.description.replace(/"/g, '""') : "";
        
        var row = [
            t.transaction_date,
            t.category_name,
            description,
            t.type.charAt(0).toUpperCase() + t.type.slice(1),
            t.amount
        ].join(',');
        
        csvContent += row + "\n";
    }

    // Create a Blob
    var blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;'}); 
    
    // Create a download link
    var link = document.createElement("a");
    var url = URL.createObjectURL(blob);
    
    link.setAttribute("href", url);
    link.setAttribute("download", "CashFlow_Report_" + new Date().toISOString().split('T')[0] + ".csv");
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}